import { useEffect, useMemo, useState } from "react";
import { useIsMounted } from "usehooks-ts";
import { Address, usePublicClient } from "wagmi";
import scaffoldConfig from "~~/scaffold.config";
import { Contract, ContractCodeStatus, ContractName, contracts } from "~~/utils/scaffold-eth/contract";

/**
 * Gets the matching contract info from the contracts file generated by `yarn deploy`
 * @param contractName - name of deployed contract
 */
export const useFactoryProductContract = <TContractName extends ContractName>(
  contractName: TContractName,
  contractAddress: Address,
  chainId?: number,
) => {
  const isMounted = useIsMounted();
  const targetNetworkId = chainId ?? scaffoldConfig.targetNetwork.id;
  const deployedContract = useMemo(
    () => ({
      ...(contracts?.[targetNetworkId]?.[0]?.contracts?.[contractName as ContractName] as Contract<TContractName>),
      ...{ address: contractAddress },
    }),
    [contractAddress, contractName, targetNetworkId],
  );
  const [status, setStatus] = useState<ContractCodeStatus>(ContractCodeStatus.LOADING);
  const publicClient = usePublicClient({ chainId: targetNetworkId });

  useEffect(() => {
    const checkContractDeployment = async () => {
      if (!deployedContract) {
        setStatus(ContractCodeStatus.NOT_FOUND);
        return;
      }
      const code = await publicClient.getBytecode({
        address: deployedContract.address,
      });

      if (!isMounted()) {
        return;
      }
      // If contract code is `0x` => no contract deployed on that address
      if (code === "0x") {
        setStatus(ContractCodeStatus.NOT_FOUND);
        return;
      }
      setStatus(ContractCodeStatus.DEPLOYED);
    };

    checkContractDeployment();
  }, [isMounted, contractName, publicClient, deployedContract]);

  return {
    data: status === ContractCodeStatus.DEPLOYED ? deployedContract : undefined,
    isLoading: status === ContractCodeStatus.LOADING,
  };
};
